import os
import sys
import glob
import subprocess
import re
import traceback

def log_error(message):
    with open("error.log", "a") as log:
        log.write(message + "\n")
    print(f"ERROR/WARNING: {message}")

def parse_stdout(stdout_path):
    """Parses the stdout.txt generated by unxwb to extract bank and file information."""
    with open(stdout_path, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()

    # Extract bank metadata
    bank_name_match = re.search(r'-\s+bank name\s+(.*)', content)
    bank_name = bank_name_match.group(1).strip() if bank_name_match else "unknown_bank"

    streaming_match = re.search(r'-\s+flags\s+.*streaming', content, re.IGNORECASE)
    is_streaming = bool(streaming_match)

    alignment_match = re.search(r'-\s+alignment\s+(\d+)', content)
    alignment = int(alignment_match.group(1)) if alignment_match else 0

    # Extract individual file entries
    files = []
    file_section = content.split('=====================================================================')
    if len(file_section) > 1:
        lines = file_section[1].split('\n')
        for line in lines:
            line = line.strip()
            # Skip empty lines, region data, and termination strings
            if not line or line.startswith('0x') or line.startswith('- finished') or line.startswith('region'):
                continue
            
            parts = line.split()
            # Ensure line represents a valid file entry (length format freq c b filename)
            if len(parts) >= 6 and parts[0].isdigit():
                files.append({
                    'length': parts[0],
                    'format': parts[1],
                    'freq': parts[2],
                    'channels': parts[3],
                    'bits': parts[4],
                    'filename': parts[5]
                })
                
    return bank_name, is_streaming, alignment, files

def generate_wave_bank_entry(bank_name, original_xwb, is_streaming, alignment, files):
    """Generates the XAP Wave Bank section for a parsed bank."""
    bank_str = "Wave Bank\n{\n"
    bank_str += f"    Name = {bank_name};\n"
    bank_str += f"    Bank File = {original_xwb};\n"
    
    if is_streaming:
        bank_str += f"    Alignment = {alignment};\n"
        bank_str += f"    Streaming = 1;\n"

    for f in files:
        name_no_ext = os.path.splitext(f['filename'])[0]
        bank_str += "\n    Entry\n    {\n"
        bank_str += f"        Name = {name_no_ext};\n"
        bank_str += f"        File = {bank_name}\\{f['filename']};\n"
        bank_str += f"        Format Tag = 0;\n"
        bank_str += f"        Channels = {f['channels']};\n"
        bank_str += f"        Sampling Rate = {f['freq']};\n"
        # XACT typically lists 'Bits Per Sample = 1' for compressed/certain PCM formats in standard XAP generation
        bank_str += f"        Bits Per Sample = 1;\n" 
        # Standard wave header size added by unxwb is 44 bytes
        bank_str += f"        Play Region Offset = 44;\n"
        bank_str += f"        Play Region Length = {f['length']};\n"
        bank_str += f"        Loop Region Offset = 0;\n"
        bank_str += f"        Loop Region Length = 0;\n"
        bank_str += f"        File Type = 0;\n"
        bank_str += "    }\n"
        
    bank_str += "}\n"
    return bank_str

def main():
    if len(sys.argv) < 2:
        print("Usage: python xwb_to_xap.py <path_to_folder_with_xwb_files>")
        sys.exit(1)

    input_folder = sys.argv[1]
    working_directory = os.getcwd()
    
    unxwb_cmd = "./unxwb.exe"

    if not os.path.isdir(input_folder):
        print(f"Error: Directory '{input_folder}' does not exist.")
        sys.exit(1)

    xwb_files = glob.glob(os.path.join(input_folder, "*.xwb"))
    if not xwb_files:
        print("No .xwb files found in the specified directory.")
        sys.exit(0)

    xap_content = "Signature = XACT;\nVersion = 9;\n\nOptions\n{\n}\n\n"
    
    for xwb_path in xwb_files:
        filename = os.path.basename(xwb_path)
        folder_name = os.path.splitext(filename)[0]
        output_dir = os.path.join(working_directory, folder_name)
        
        print(f"Processing: {filename}")
        
        try:
            os.makedirs(output_dir, exist_ok=True)
            
            abs_xwb_path = os.path.abspath(xwb_path)
            stdout_path = os.path.join(output_dir, "stdout.txt")
            
            with open(stdout_path, "w") as out_file:
                process = subprocess.run(
                    [unxwb_cmd, "-v", abs_xwb_path],
                    cwd=output_dir,
                    stdout=out_file,
                    stderr=subprocess.STDOUT,
                    text=True
                )
                
            if process.returncode != 0:
                log_error(f"unxwb.exe returned non-zero exit code ({process.returncode}) for {filename}")

            bank_name, is_streaming, alignment, files = parse_stdout(stdout_path)
            
            if not files:
                log_error(f"Warning: No files parsed from {filename}. Check stdout.txt.")
            
            xap_content += generate_wave_bank_entry(
                bank_name=bank_name,
                original_xwb=filename,
                is_streaming=is_streaming,
                alignment=alignment,
                files=files
            )

        except Exception as e:
            error_msg = f"Failed processing {filename}: {str(e)}\n{traceback.format_exc()}"
            log_error(error_msg)

    xap_path = os.path.join(working_directory, "Audio.xap")
    try:
        with open(xap_path, "w", encoding="utf-8") as xap_file:
            xap_file.write(xap_content)
        print(f"\nSuccessfully generated XAP file: {xap_path}")
    except Exception as e:
        log_error(f"Failed to write Audio.xap: {str(e)}")

if __name__ == "__main__":
    main()